server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiradaus
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console.enable: true

app:
  jwt:
    secret: "tiradaus-app"
    expiration: 3600
    issuer: "org.tiradaus"

management:
  endpoints.web.exposure.include: health, info
