server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driveClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2:
    console.enable: true

app:
  jwt:
    secret: "tiradaus-app"
    expiration: 3600
    issuer: "org.tiradaus"

management:
  endpoints.web.exposure.include: health, info
